name: your_project_name
description: A Flutter app for IoT device discovery and control.
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  http: ^0.13.4
  universal_html: ^2.0.8
  multicast_dns: 0.3.3
  flutter_svg: ^2.0.9
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons/