// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2cSLQvwnjz3qF7hMCE_GHMWkEj25w14',
    appId: '1:283494879532:web:c7d20dc224ff0ecc2a5c89',
    messagingSenderId: '283494879532',
    projectId: 'application-spark-74299',
    authDomain: 'application-spark-74299.firebaseapp.com',
    storageBucket: 'application-spark-74299.firebasestorage.app',
    measurementId: 'G-R3X6H3ZY19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRRoOxB-CSd0hyygG7ohq3_xF-7IpoX-w',
    appId: '1:283494879532:android:68fc8d882d71f94c2a5c89',
    messagingSenderId: '283494879532',
    projectId: 'application-spark-74299',
    storageBucket: 'application-spark-74299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNi751SDc7IJqpYnI8hFPC-13W84pIMVs',
    appId: '1:283494879532:ios:01b8278b34a4759a2a5c89',
    messagingSenderId: '283494879532',
    projectId: 'application-spark-74299',
    storageBucket: 'application-spark-74299.firebasestorage.app',
    iosBundleId: 'com.example.projectSpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNi751SDc7IJqpYnI8hFPC-13W84pIMVs',
    appId: '1:283494879532:ios:01b8278b34a4759a2a5c89',
    messagingSenderId: '283494879532',
    projectId: 'application-spark-74299',
    storageBucket: 'application-spark-74299.firebasestorage.app',
    iosBundleId: 'com.example.projectSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY2cSLQvwnjz3qF7hMCE_GHMWkEj25w14',
    appId: '1:283494879532:web:500ff3a3dba11e5a2a5c89',
    messagingSenderId: '283494879532',
    projectId: 'application-spark-74299',
    authDomain: 'application-spark-74299.firebaseapp.com',
    storageBucket: 'application-spark-74299.firebasestorage.app',
    measurementId: 'G-E3YHFNXVTV',
  );
}